name: playground.htsuyoshiy.online

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Vite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install ./home

      - name: Build website
        env:
          NODE_ENV: production
        run: npm run build -C ./home

      - name: Upload to S3
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./home/dist/ s3://${{ secrets.AWS_S3_BUCKET }} --exclude="*.md" --exclude=".git"

      - name: Delete extra files in /assets
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./home/dist/assets/ s3://${{ secrets.AWS_S3_BUCKET }}/assets --delete --exclude="*.md" --exclude=".git"
